import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import Link from "next/link";
import { Toaster } from "react-hot-toast";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
        <Toaster position="top-center"/>
          <nav className="">
            <div className="flex gap-3 bg-slate-400 p-4">
              <Link href={"/login"} className="hover:text-white">
                Login
              </Link>
              <Link href={"/signup"} className="hover:text-white">
                signup
              </Link>
              <Link href={"/profile"} className="hover:text-white">
                profile
              </Link>
            </div>
          </nav>

          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
